name: portfolio-mobile-app

static_sites:
  - name: web
    github:
      repo: binsager86-cmd/Portfolio-Mobile-App
      branch: main
      deploy_on_push: true
    build_command: npm install && npx expo export --platform web --clear
    output_dir: dist
    environment_slug: node-js
    envs:
      - key: EXPO_PUBLIC_API_URL
        value: "https://backend-api-app-hfc2n.ondigitalocean.app"
        scope: BUILD_TIME
      - key: EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID
        value: "549902495569-6kbcenrhcir2iqskj377fm561e8e6l50.apps.googleusercontent.com"
        scope: BUILD_TIME
    catchall_document: index.html
    error_document: index.html
    cors:
      allow_origins:
        - exact: "https://backend-api-app-hfc2n.ondigitalocean.app"
